### ISSUE TITLE
widen and narrow with MSVC C++latest

### ISSUE THREAD

**Issue by jimorc** [boostorg/nowide#135]
I am not sure where this problem fits, but changes to nowide would fix it:
Using MSVC and compiling for C++17, the following code compiles and executes:

```c_cpp
std::string str = u8"🕳️💚💜";
std::wstring wide = nowide::widen(str);
```

If I were to print wide out or display it in a Win32 MessageBox, the correct text is displayed.

If I try this with MSVC C++latest, I must define `str` as:
```c_cpp
std::u8string str = u8"🕳️💚💜";
```

But `nowide::widen` does not accept `u8string`s. I also cannot remove the `u8` at the start of the string because then the compiler complains that the string contains characters that are not in the code page.

Suggestion: Update `nowide::widen` to take `u8string`s as input, and update `nowide::narrow` to output `u8string`s.

**Comment by jimorc** [comment]
I have found that if I change the code page to UTF-8, I can remove the `u8` from the start of the string, and the code works. However, that is not a general solution.

**Comment by Flamefire** [comment]
Accepting an u8string should already be possible, as Nowide should understand u8char: https://github.com/boostorg/nowide/blob/develop/include/boost/nowide/detail/is_string_container.hpp#L43
Have you tried with the latest Nowide?

As it is impossible to overload a function on the return type the 2nd suggestion of returning an u8string is unfortunately not possible. But you can use the underlying convert_string function: https://github.com/boostorg/nowide/blob/develop/include/boost/nowide/utf/convert.hpp#L75

**Comment by jimorc** [comment]
Thank you Flamefire for the quick answer. My problem was I downloaded the nowhere_standalone version from some page that said to download the latest standalone version, but it pointed to a version from 2017. Now that I have downloaded the latest standalone version from the GitHub repository, the code works.

Thanks again.

**Comment by Flamefire** [comment]
Glad to hear!
