### ISSUE TITLE
Missing diagnostics in args

### ISSUE THREAD

**Issue by rob-stewart** [boostorg/nowide#15]
In args.hpp:88-94, in fix_args(), you silently ignore CommandLineToArgvW() errors. According to https://msdn.microsoft.com/en-us/library/windows/desktop/bb776391(v=vs.85).aspx, you should call GetLastError() to determine why CommandLineToArgvW() returns NULL.

**Comment by artyom-beilis** [comment]
The question is what do I do about it? I can set some error code but in general I don't think throwing an exception will be expected behavior.

**Comment by rob-stewart** [comment]
In args.hpp:99, in fix_args(), you silently truncate the command line if basic_stackstring::convert() returns a null pointer, which can mean unrecognized characters or there was insufficient buffer space (so the choice of short_stackstring was faulty). Silently discarding command line input is a terrible idea.

**Comment by rob-stewart** [comment]
In args.hpp:126-136, in fix_env(), you silently ignore failure to convert the environment block. Library users should be made aware of the failure.

**Comment by rob-stewart** [comment]
There must be some mechanism for alerting users to failures. Why don't you think an exception is the expected behavior? I realize that you can't work around these failures, but you can't allow library users to think all's well when it isn't.

**Comment by artyom-beilis** [comment]
- Regarding stack_string if there is no enough space - the memory is allocated.
- Also as the result of the review I'm going to change instead discarding entire string I'll replace invalid characters with U-FFFD replacement character. So virtually there are no cases when conversion will fail. 
- Same will be valid for env. so Unless basic function like GetEnvironmentStringsW fails - which basically means we don't have env. variables.

**Comment by artyom-beilis** [comment]
Note: converting invalid characters to U-FFFD is actually consistent with what modern WinAPI does.

**Comment by rob-stewart** [comment]
The overarching criteria should be that any WIN32 API failure must be reported; silently not producing the expected result is not acceptable. Using U-FFFD is reasonable where applicable, but library users must still be informed. For example, you might provide a status check that permits users to discover that you had to use U-FFFD in at least one case so users will know when there are issues. (A library user might use that information to alert a human that things didn't go as well as planned and offer the option to continue or quit.)

**Comment by artyom-beilis** [comment]
Reasonable

**Comment by Flamefire** [comment]
I agree with the reasoning that a failed WinAPI call at this place must be handled as an error situation. Also there is nothing one can do about this so in pretty much all cases a termination of the program is justified. So an exception is exactly what should happen here as the program will most likely not be able to run with that. See #29
