### ISSUE TITLE
Cannot move ifstream

### ISSUE THREAD

**Issue by egorpugin** [boostorg/nowide#18]
Hi!

I'm playing with nowide and tried to replace `std::ifstream` in my code with nowide one.
But move operator is deleted. (VS2017 - v15.2 - the latest).
```
d->ifile = std::move(boost::nowide::ifstream(f.string(), std::ifstream::binary));
```

```
error C2280: 'boost::nowide::basic_ifstream<char,std::char_traits<char>> &boost::nowide::basic_ifstream<char,std::char_traits<char>>::operator =(const boost::nowide::basic_ifstream<char,std::char_traits<char>> &)': attempting to reference a deleted function
```

VS points me to `fstream.hpp:109`:
```
private:
        boost::scoped_ptr<internal_buffer_type> buf_;
```

I workarounded it with `.open()`, but still...
Is this actually a bug or a feature?

**Comment by artyom-beilis** [comment]
Currently it does not support C++11 move constructor, will be addressed upon inclusion to boost

**Comment by egorpugin** [comment]
Do you plan to add `boost::nowide::wofstream` also?
Because now nowide don't have it and when I write
```
typedef boost::nowide::basic_ofstream<wchar_t> wofstream;
wofstream ofile(p.string(), std::ios::out | std::ios::binary);
```
compiler says there's no `boost::nowide::basic_filebuf<CharType,Traits>` with wchar_t specialization.
Indeed there's only `char` one.

**Comment by artyom-beilis** [comment]
No I don't plan to add wfstream , since the library is nowide .
