### ISSUE TITLE
Test libraries and executables should be declared EXCLUDE_FROM_ALL

### ISSUE THREAD

**Issue by pdimov** [boostorg/nowide#181]
The Boost convention is that `cmake --build .` only builds the libraries. Test libraries and executables are built with `cmake --build . --target tests`.

**Comment by Flamefire** [comment]
Is it? I was only aware of this idiom:
```
if(BUILD_TESTING)
  add_subdirectory(test)
endif()
```

As that is what is usually done with `cmake --build .` or `make (all)`: Build everything (unless disabled). Or am I mistaken?

**Comment by pdimov** [comment]
It is.

Ideally, we should even have fine-grained, per library, test targets, e.g. `cmake --build . --target boost_nowide_tests` or similar, although I haven't yet nailed this down or implemented it.

While in b2 you can say `b2 libs/nowide/test`, and this will build the test executables of Nowide with their dependencies, and run them, there's no equivalent in CMake, so we have to do that ourselves, somehow.
