### ISSUE TITLE
Build with exceptions disabled is not supported

### ISSUE THREAD

**Issue by ivaigult** [boostorg/nowide#19]
Not really an issue, but feature request. 

I reviewed library source code and it doesn't seem to rely on exceptions heavily. It just need replacement from `try` to `BOOST_TRY`,  `catch` to  `BOOST_CATCH` and so on. Also , `throw()` or `nothrow` need to be replaced to appropriated macros.

**Comment by Flamefire** [comment]
Do you have a real use case for this?

**Comment by Flamefire** [comment]
Closing this old feature request due to inactivity
