### ISSUE TITLE
utf8_codecvt.hpp has CRLF line terminators

### ISSUE THREAD

**Issue by kivadiu** [boostorg/nowide#34]
This file is the only one that has CRLF line terminators. Other have only LF (unix). Why?
Could all the files have the same line ending?

**Comment by artyom-beilis** [comment]
Ok I'll check

**Comment by kivadiu** [comment]
Fixed here: https://github.com/artyom-beilis/nowide/pull/38

**Comment by Flamefire** [comment]
Fixed by 98cda02 and 668a526
