### ISSUE TITLE
Feature Request: support for stat?

### ISSUE THREAD

**Issue by thehans** [boostorg/nowide#43]
Do you think it would be within scope of this project to support stat such that utf8 strings can be passed to it and it would call wstat with the proper utf8->utf16 conversion underneath?

**Comment by Flamefire** [comment]
AFAIK `stat` is a POSIX-only function and I don't know of any `wstat` function. Can you point me to the documentation of it if there is one? I think it does not apply to Windows as the return value of `stat` is very POSIX specific.

**Comment by pdimov** [comment]
`_wstat`, https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/stat-functions?view=vs-2019

**Comment by Flamefire** [comment]
This is mainly MSVC only, isn't it? What to do for others? I guess it will be a trial-and-error. Well, if we put it in an extra header, why not?

**Comment by Berrysoft** [comment]
> This is mainly MSVC only, isn't it?

No, it's part of CRT of Windows, which means MinGW can also get use of it.

**Comment by Flamefire** [comment]
I looked into this and found the following which needs to be addressed:
- `stat` is available on non-Windows even with `-std=c++11` set -> OK
- As with other `w*` functions in cygwin/mingw I expect them to be not available for `-std=c++xx` which means they need to be defined in a CPP file
- `stat` on non-Windows may report sizes in 32bit types on 32bit systems and set an error on overflow
- `stat` on Windows uses a 64 or 32 bit time field depending on a macro and a 32bit file size. There is no indication that an error will be set for large files
- minor: `wstat` has an issue with Windows Vista and symbolic links which is not the case for `stat` --> WTF?

So in conclusion:
- On Linux we may or may not get 64bit types but have an error set when a to-large-file is `stat`ed -> OK
- On Windows `wstat` needs to be called in a cpp file but the stat-struct may change size depending on defines

--> Proposal: Define a typedef `boost::nowide::_stat` which points to `struct _stat` on Linux and `_stat64` on Windows and use `_wstat64` to query the information. This way the type doesn't change the size.

It is also possible to provide an overload which accepts a `struct _stat` and internally passes it's size to the cpp file and return an error if the size mismatches. This allows to detect differing defines (`_USE_32BIT_TIME_T`) but may silently report wrong sizes for large files. 

PS: Does anyone else want a different struct name for the data returned which does not clash with the function name?

**Comment by Flamefire** [comment]
@thehans I'd like to invite you (and everyone else) to take a look at #108 which implements this. Check if it suits your needs.

Thanks!

**Comment by thehans** [comment]
@Flamefire Thank you very much for implementing this, and sorry I wasn't able to provide any timely feedback.  
When I opened this feature request, I was working on adding nowide to an existing project, and never quite finished that PR (only partly because of wanting `stat`).  I'm still interested to try it out, and that PR is still open and waiting for me to update and finalize, just not sure when I'll have time to get back into it.

And congratulations on being added to official Boost releases! :tada:

**Comment by Flamefire** [comment]
@thehans All good. The upcoming Boost release 1.74 will contain the feature and as usual you can try it out already by using this git repository directly with and without boost. So feel free to test it and if you notice any problems please open a new issue here
