### ISSUE TITLE
standalone build broken

### ISSUE THREAD

**Issue by rwiesenfarth** [boostorg/nowide#72]
Broken since c3dd00723f21a20fe5afb83f19c3eea8cbf9f4b1

The removal of standalone/CMakeLists.txt breaks the script standalone/convert and thus the complete standalone version of nowide.

Users interested in nowide are now forced to use Boost. Is this really intentional?

**Comment by Flamefire** [comment]
Yes. I'm still working on bringing this to a release ready state. Last thing remaining is C++11 support (move). Afterwards I'll update the stand-alone conversion script and add tests similar to what I did in my fork. The reason for removal of that CML is that I want a single-source version. So even the CMakeLists need to be generated out of the real CML which avoids different behavior of those versions.

I'll also add tagged releases with ready-to-use tarballs of the standalone version
