### ISSUE TITLE
std::getline on boost::nowide::cin contains CR

### ISSUE THREAD

**Issue by Alexander12365** [boostorg/nowide#94]
Dear Team of boost!

I have an issue with the recently added library nowide.

Compiler: tdm64-gcc-9.2.0.exe from https://jmeubank.github.io/tdm-gcc/ which is MinGW-w64 based
OS: Windows 10 64bit
Target: Building a Console Application using CodeBlocks.

The problem arises when I am using getline during an endless loop with console input.
If invalid user input is given with the CTRL-Key then the getline command keeps failing to read the following inputs.

When I was using wcout, the issue was solved calling fflush(stdin) after an incorrect input which does not work when using boost::nowide.

Here is an example source code (renamed extension from .cpp to .txt so I was able to upload it)
[getline_issue.txt](https://github.com/boostorg/nowide/files/4574327/getline_issue.txt)

Regards,
Alexander Zinkl

**Comment by Flamefire** [comment]
Can you elaborate what you mean by "invalid user input is given with the CTRL-Key"? What exactly do you have to input into the console to trigger this bug?

Will try to reproduce later when I'm back on my Win machine.

**Comment by Alexander12365** [comment]
When I am pressing Ctrl+Any other key to intentionally produce invalid input, such that the Console displays:
![Ctrl+Other Keys](https://user-images.githubusercontent.com/128189/80967909-6cdc7280-8e17-11ea-8be2-4d58b48ae685.png)

**Comment by Flamefire** [comment]
I was unable to reproduce this issue with MSVC 2019. However I noticed that contrary to `std::cin` control characters are not handled specially. So you see e.g. `\r` in the string and any other control character. Besides that the next input works fine

Is that maybe the issue you see? You are comparing to `"1"` not to `"1\r"` which might be why it fails.

Why do you think `getline` keeps failing? The example code doesn't check it

**Comment by Alexander12365** [comment]
No the issue im seeing is that when I input something invalid with the Control key  + Another key that all following inputs are invalid (meaning the getline doesnt read what im actually inputting?)
![invalid inputs](https://user-images.githubusercontent.com/128189/80990149-3b26d400-8e36-11ea-9e68-f333566778a8.png)

**Comment by Flamefire** [comment]
And if you don't input something with the control key, does your program work?   
For me it does not because the input is actually "1\r" not "1"

**Comment by Alexander12365** [comment]
Indeed I just noticed that, which is also different from my wcout solution.

**Comment by Alexander12365** [comment]
Apparently the escape sequence is still contained within the string whereas previously it was not.

**Comment by Flamefire** [comment]
Ok, then this is the issue. I'm uncertain what to do with control characters, they are returned by the underlying API call.

I'll experiment a bit and will try to match the cin behavior on MSVC 2019

**Comment by Alexander12365** [comment]
Yes I just fixed my issue by erasing the last character, which I did not have to do before. Thank you for your quick responses!

**Comment by Flamefire** [comment]
Please make sure you only trim trailing `\r` characters, not blindly remove the last char. I just opened a PR which will ignore the \r characters to match the std::cin implementation

**Comment by Alexander12365** [comment]
Thanks, I just changed that.

I am going to close this issue then.
