### ISSUE TITLE
Maintainers missing from meta/libraries.json

### ISSUE THREAD

**Issue by mloskot** [boostorg/nowide#98]
The current metadata only contain the author info

https://github.com/boostorg/nowide/blob/3f202c6b3854c035bd1980108c3b9e9acd0001f1/meta/libraries.json#L4-L6

The info about the current maintainer is missing:

```
"maintainers": [
        "Alexander Grund <...-at- ...>"
]
```

**Comment by Flamefire** [comment]
Thanks, done in 23f5f89
